### ISSUE TITLE
FindMutations and MutationStats class

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#161]
These two classes aim to refactor call.cc into more manageable scale.
- `FindMutation` class - Handle workspace_t and peeling forward/backward.
- `MutationStats` class - Calculate and store all stats in DNG.

This will be break into several (n=?) PR. Each PR will address one or a few of the following (subject to change).
- [x] Refactor FindMutation from call.cc into it's own class without any additional changes. #159 
- [x] Unittest for FindMutation.
- [x] Move stats from FindMutation to MutationStats
  - [x] PR 1 - Introduce MutationStast class, unittest, and a few basic stats such as Prob of Mutation, genotype, and posterior. #162, #164.
  - [x] PR 2 - Move all stats in FindMutation to MutationStats #179.
- [ ] Move stats in call.cc to MutationStats (maybe break into 2 PRs).
- [ ] Remove stats_t from call.cc, FindMutation class.
- [ ] Customizable output stats from MutationStats (minimum, basic, everything).

**Comment by reedacartwright** [comment]
Feature implemented, but in a different way.
