### ISSUE TITLE
Support different inheritance patterns

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#54]
Implement a new command line option `--pattern` that supports different modes of inheritance.  This will require the pedigree to generate different peeling operations depending on the inheritance mode.

**Possible Values**
- `autosomal` (the default)
- `xlinked` (females have 2 copies, males have 1; males transmit to daughters, not to sons)
- `ylinked` (males have 1 copy, only transmits it to sons)
-  `wlinked` (females have 1 copy, only transmited to daughters)
- `zlinked` (males have 2 copies, females have 1; females transmit to sons, not to daughters)
- `maternal` (transmitted by mother to child)
- `paternal` (transmitter by father to child)

The program should recognize abbreviations of the values.

TODO:
- [x] After issue #85  (create test cases for current pedigree parsing algorithm)

**Comment by stevenhwu** [comment]
Previous and future PR:
- [x] Refactor RelationshipGraph Class #190
- [x] Introduce multiple inheritance model #193
- [ ] Add tests and R codes for mutation/peeling #194
- [ ] Introduce Y_Linked inheritance model #197
- [ ] Introduce X_Linked inheritance model
