### ISSUE TITLE
Test pedigree

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#85]
**TODO list**
- [x] Refactor pedigree
- [x] Test pedigree.cc
  - [x] on trio
  - [x] bigger pedigree with 12 members
- [ ] Maybe some restructure required in order to implement issue #54 
- [ ] Generate and test random pedigree. related to #87 

This will be done through several PRs.
- 1st PR #173: Only update the testdata commit id and SHA256
- 2nd PR #187: Rename Pedigree to RelationshipGraph
- 3rd PR #190: Refactor `RelationshipGraph` and add more unittest

Future PRs will include the following;
- [x] Renaming pedigree.cc to relationship_graph.cc. 
- [x] Adding basic unittest (maybe only 1 or 2 tests)
- [x] Adding unittest with 12 members
- [x] Refactoring RelationshipGraph class
- [x] Unittest each steps/functions in the RelationshipGraph class

BONUS (Low priority)
- [ ] Print out pedigree as ASCII art.

**Comment by stevenhwu** [comment]
- Going to close this issue, majority of the core tasks are done. Started working on #54, so any additional restructure and refactor will be related to #54.
- Generate and test random pedigree. related to #87. This can be stand alone 
- Print out pedigree as ASCII art. @anderspitman is working on a even better version to replace this.
